# Generated by Django 2.2.2 on 2021-12-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_image',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
